### ISSUE TITLE
Simplify manifest once we have new ETL

### ISSUE THREAD

**Issue by rossjones** [datagovuk/apiserver#9]
We really just want table settings, something like

``` yaml
database: name
table: name 
fields:
    - name: fieldname
      type: optional type
      limited_set: true  # has limited choices so can be distinct
      filter: true 
      indexed: true 
      unique: true 
    - name:....
```

It's entirely possible we can work ALL of this out given the database.table ...
